/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Customer_07_Kavindi;

import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Janiya's PC
 */
public class Customer_Details extends javax.swing.JPanel {

    /**
     * Creates new form Customer_Details
     */
    public Customer_Details() {
        initComponents();
        GenerateID();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Save = new javax.swing.JButton();
        add_1 = new javax.swing.JTextField();
        Update = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        cus_id = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        c_name = new javax.swing.JTextField();
        add_2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        add_3 = new javax.swing.JTextField();
        city_c = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        Tel_no = new javax.swing.JTextField();
        nic = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        Tel_home = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        Dis_no = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Customer Details");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Address Line 1");

        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        Save.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SaveKeyReleased(evt);
            }
        });

        add_1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add_1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                add_1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                add_1FocusLost(evt);
            }
        });
        add_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_1ActionPerformed(evt);
            }
        });
        add_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                add_1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                add_1KeyTyped(evt);
            }
        });

        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        Update.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                UpdateKeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Customer Name");

        cus_id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cus_id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cus_idFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cus_idFocusLost(evt);
            }
        });
        cus_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cus_idActionPerformed(evt);
            }
        });
        cus_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cus_idKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cus_idKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Customer  ID");

        c_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        c_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                c_nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                c_nameFocusLost(evt);
            }
        });
        c_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_nameActionPerformed(evt);
            }
        });
        c_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                c_nameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                c_nameKeyTyped(evt);
            }
        });

        add_2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add_2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                add_2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                add_2FocusLost(evt);
            }
        });
        add_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_2ActionPerformed(evt);
            }
        });
        add_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                add_2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                add_2KeyTyped(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Address Line 2");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("City");

        add_3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add_3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                add_3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                add_3FocusLost(evt);
            }
        });
        add_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_3ActionPerformed(evt);
            }
        });
        add_3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                add_3KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                add_3KeyTyped(evt);
            }
        });

        city_c.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        city_c.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                city_cFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                city_cFocusLost(evt);
            }
        });
        city_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                city_cActionPerformed(evt);
            }
        });
        city_c.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                city_cKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                city_cKeyTyped(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("Address Line 3");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("Contact Number Home");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("Date Of Birth");

        Tel_no.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Tel_no.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Tel_noFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Tel_noFocusLost(evt);
            }
        });
        Tel_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tel_noActionPerformed(evt);
            }
        });
        Tel_no.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Tel_noKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Tel_noKeyTyped(evt);
            }
        });

        nic.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nic.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nicFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nicFocusLost(evt);
            }
        });
        nic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicActionPerformed(evt);
            }
        });
        nic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nicKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nicKeyTyped(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("NIC");

        Tel_home.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Tel_home.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Tel_homeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Tel_homeFocusLost(evt);
            }
        });
        Tel_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tel_homeActionPerformed(evt);
            }
        });
        Tel_home.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Tel_homeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Tel_homeKeyTyped(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("Contact Number");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel23.setText("Status");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel24.setText("Gender");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel25.setText("Loyalty Discount No");

        Dis_no.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Dis_no.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Dis_noFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Dis_noFocusLost(evt);
            }
        });
        Dis_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dis_noActionPerformed(evt);
            }
        });
        Dis_no.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Dis_noKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Dis_noKeyTyped(evt);
            }
        });

        buttonGroup2.add(jCheckBox1);
        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Active");
        jCheckBox1.setContentAreaFilled(false);
        jCheckBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jCheckBox1KeyReleased(evt);
            }
        });

        buttonGroup2.add(jCheckBox2);
        jCheckBox2.setText("Inactive");
        jCheckBox2.setContentAreaFilled(false);

        buttonGroup1.add(jCheckBox3);
        jCheckBox3.setText("Male");
        jCheckBox3.setContentAreaFilled(false);
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        jCheckBox3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jCheckBox3KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jCheckBox3KeyTyped(evt);
            }
        });

        buttonGroup1.add(jCheckBox4);
        jCheckBox4.setText("Female");
        jCheckBox4.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(cus_id, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(c_name, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel14)
                        .addGap(202, 202, 202)
                        .addComponent(add_1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel16)
                        .addGap(202, 202, 202)
                        .addComponent(add_2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel18)
                        .addGap(202, 202, 202)
                        .addComponent(add_3, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel17)
                        .addGap(266, 266, 266)
                        .addComponent(city_c, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel22)
                        .addGap(188, 188, 188)
                        .addComponent(Tel_no, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel19)
                        .addGap(148, 148, 148)
                        .addComponent(Tel_home, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel21)
                        .addGap(268, 268, 268)
                        .addComponent(nic, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel25)
                        .addGap(166, 166, 166)
                        .addComponent(Dis_no, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel23)
                        .addGap(251, 251, 251)
                        .addComponent(jCheckBox1)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(592, 592, 592)
                        .addComponent(Update)
                        .addGap(10, 10, 10)
                        .addComponent(Save))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel20))
                        .addGap(211, 211, 211)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jCheckBox3)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox4))
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel15)
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel13))
                    .addComponent(cus_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel9))
                    .addComponent(c_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel14))
                    .addComponent(add_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel16))
                    .addComponent(add_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel18))
                    .addComponent(add_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel17))
                    .addComponent(city_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel22))
                    .addComponent(Tel_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(Tel_home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(nic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox4))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel25))
                    .addComponent(Dis_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel23))
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Update)
                    .addComponent(Save))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        if (cus_id.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter customer id ");
            cus_id.grabFocus();
        } else if (c_name.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter customer name ");
            c_name.grabFocus();
        } else if (Tel_no.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter contact number ");
            Tel_no.grabFocus();
        } else if (nic.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter NIC ");
            nic.grabFocus();
        } else if (Dis_no.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter Loyalty discount No");
            Dis_no.grabFocus();
        } else {
            String status = "";
            if (jCheckBox1.isSelected()) {
                status = "1";
            } else if (jCheckBox2.isSelected()) {
                status = "0";
            }
            String gender = "";
            if (jCheckBox3.isSelected()) {
                gender = "Male";
            } else {
                gender = "Female";
            }

            Date d1 = jDateChooser1.getDate();
            SimpleDateFormat sf = new SimpleDateFormat("yyyy-MM-dd");
            String d = sf.format(d1);
            int k = JOptionPane.showConfirmDialog(this, "Do you want to save this data ?", "WARNING !", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (k == 0) {

                try {
                    //                idcustomer, name, address_1, address_2, address_3, city, tp1, tp2, nic, dob, gender, status, loyalty_discount_idloyalty_discount
                    DB.MyDB.iud("insert into customer values('" + cus_id.getText() + "','" + c_name.getText() + "','" + add_1.getText() + "','" + add_2.getText() + "','" + add_3.getText() + "','" + city_c.getText() + "','" + Tel_no.getText() + "','" + Tel_home.getText() + "','" + nic.getText() + "','" + d + "','" + gender + "','" + status + "','" + Dis_no.getText() + "')");
                    JOptionPane.showMessageDialog(this, "Successfully Saved !");
                    Customer_Search.Search();

                    cus_id.setText("");
                    c_name.setText("");
                    add_1.setText("");
                    add_2.setText("");
                    add_3.setText("");
                    city_c.setText("");
                    Tel_no.setText("");
                    Tel_home.setText("");
                    nic.setText("");
                    Dis_no.setText("");
                    jCheckBox3.setSelectedIcon(null);
                    jCheckBox4.setSelectedIcon(null);
                    Dis_no.setText("");
                    jCheckBox1.setSelected(true);
                    GenerateID();
                    cus_id.grabFocus();

                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_SaveActionPerformed

    private void SaveKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SaveKeyReleased
        char c = (char) evt.getKeyCode();
        if (c == KeyEvent.VK_LEFT) {
            Update.grabFocus();
        }
    }//GEN-LAST:event_SaveKeyReleased

    private void cus_idFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cus_idFocusGained
        cus_id.selectAll();
    }//GEN-LAST:event_cus_idFocusGained

    private void cus_idFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cus_idFocusLost

    }//GEN-LAST:event_cus_idFocusLost

    private void cus_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cus_idActionPerformed
        search();
    }//GEN-LAST:event_cus_idActionPerformed
    Customer_Search cs;
    private void cus_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cus_idKeyReleased
        char c = (char) evt.getKeyCode();
        if (c == KeyEvent.VK_DOWN) {
            c_name.grabFocus();
        } else if (c == KeyEvent.VK_F2) {
            if (cs == null) {
                cs = new Customer_Search();
                cs.setVisible(true);
            } else {
                cs.setVisible(true);
            }
        }
    }//GEN-LAST:event_cus_idKeyReleased

    private void cus_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cus_idKeyTyped

    }//GEN-LAST:event_cus_idKeyTyped

    private void c_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_c_nameFocusGained
        c_name.selectAll();
    }//GEN-LAST:event_c_nameFocusGained

    private void c_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_c_nameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_c_nameFocusLost

    private void c_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_nameActionPerformed
        add_1.grabFocus();
    }//GEN-LAST:event_c_nameActionPerformed

    private void c_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c_nameKeyReleased
        char c = (char) evt.getKeyCode();
        if (c == KeyEvent.VK_UP) {
            cus_id.grabFocus();
        }
        if (c == KeyEvent.VK_DOWN) {
            add_1.grabFocus();
        }
    }//GEN-LAST:event_c_nameKeyReleased

    private void c_nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c_nameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_c_nameKeyTyped

    private void add_2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_add_2FocusGained
        add_2.selectAll();
    }//GEN-LAST:event_add_2FocusGained

    private void add_2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_add_2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_add_2FocusLost

    private void add_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_2ActionPerformed
        add_3.grabFocus();
    }//GEN-LAST:event_add_2ActionPerformed

    private void add_2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_add_2KeyReleased
        char c = (char) evt.getKeyCode();
        if (c == KeyEvent.VK_UP) {
            add_1.grabFocus();
        }
        if (c == KeyEvent.VK_DOWN) {
            add_3.grabFocus();
        }
    }//GEN-LAST:event_add_2KeyReleased

    private void add_2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_add_2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_add_2KeyTyped

    private void add_3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_add_3FocusGained
        add_3.selectAll();
    }//GEN-LAST:event_add_3FocusGained

    private void add_3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_add_3FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_add_3FocusLost

    private void add_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_3ActionPerformed
        city_c.grabFocus();
    }//GEN-LAST:event_add_3ActionPerformed

    private void add_3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_add_3KeyReleased
        char c = (char) evt.getKeyCode();
        if (c == KeyEvent.VK_UP) {
            add_2.grabFocus();
        }
        if (c == KeyEvent.VK_DOWN) {
            city_c.grabFocus();
        }
    }//GEN-LAST:event_add_3KeyReleased

    private void add_3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_add_3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_add_3KeyTyped

    private void city_cFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_city_cFocusGained
        city_c.selectAll();
    }//GEN-LAST:event_city_cFocusGained

    private void city_cFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_city_cFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_city_cFocusLost

    private void city_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_city_cActionPerformed
        Tel_no.grabFocus();
    }//GEN-LAST:event_city_cActionPerformed

    private void city_cKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_city_cKeyReleased
        char c = (char) evt.getKeyCode();
        if (c == KeyEvent.VK_UP) {
            add_3.grabFocus();
        }
        if (c == KeyEvent.VK_DOWN) {
            Tel_no.grabFocus();
        }
    }//GEN-LAST:event_city_cKeyReleased

    private void city_cKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_city_cKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_city_cKeyTyped

    private void Tel_noFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Tel_noFocusGained
        Tel_no.selectAll();
    }//GEN-LAST:event_Tel_noFocusGained

    private void Tel_noFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Tel_noFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_Tel_noFocusLost

    private void Tel_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tel_noActionPerformed
        Tel_home.grabFocus();
    }//GEN-LAST:event_Tel_noActionPerformed

    private void Tel_noKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Tel_noKeyReleased
        char c = (char) evt.getKeyCode();
        if (c == KeyEvent.VK_UP) {
            city_c.grabFocus();
        }
        if (c == KeyEvent.VK_DOWN) {
            Tel_home.grabFocus();
        }
    }//GEN-LAST:event_Tel_noKeyReleased

    private void Tel_noKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Tel_noKeyTyped

        //validaion for phone number
        if (!(Character.isDigit(evt.getKeyChar()))) {
            evt.consume();
        }
        if (Tel_no.getText().length() > 9) {
            evt.consume();
        }
    }//GEN-LAST:event_Tel_noKeyTyped

    private void nicFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nicFocusGained
        //for select all
        nic.selectAll();
    }//GEN-LAST:event_nicFocusGained

    private void nicFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nicFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_nicFocusLost

    private void nicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicActionPerformed
        Dis_no.grabFocus();
    }//GEN-LAST:event_nicActionPerformed

    private void nicKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nicKeyReleased
        //to going up and down using arrow keys
        char c = (char) evt.getKeyCode();
        if (c == KeyEvent.VK_UP) {
            Tel_home.grabFocus();
        }
        if (c == KeyEvent.VK_DOWN) {
            jDateChooser1.grabFocus();
        }
    }//GEN-LAST:event_nicKeyReleased

    private void nicKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nicKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_nicKeyTyped

    private void Tel_homeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Tel_homeFocusGained
        Tel_home.selectAll();
    }//GEN-LAST:event_Tel_homeFocusGained

    private void Tel_homeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Tel_homeFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_Tel_homeFocusLost

    private void Tel_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tel_homeActionPerformed
        nic.grabFocus();
    }//GEN-LAST:event_Tel_homeActionPerformed

    private void Tel_homeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Tel_homeKeyReleased
        char c = (char) evt.getKeyCode();
        if (c == KeyEvent.VK_UP) {
            Tel_no.grabFocus();
        }
        if (c == KeyEvent.VK_DOWN) {
            nic.grabFocus();
        }
    }//GEN-LAST:event_Tel_homeKeyReleased

    private void Tel_homeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Tel_homeKeyTyped
        //validation for home phone number
        if (!(Character.isDigit(evt.getKeyChar()))) {
            evt.consume();
        }
        if (Tel_home.getText().length() > 9) {
            evt.consume();
        }
    }//GEN-LAST:event_Tel_homeKeyTyped

    private void Dis_noFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Dis_noFocusGained
        Dis_no.selectAll();
    }//GEN-LAST:event_Dis_noFocusGained

    private void Dis_noFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Dis_noFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_Dis_noFocusLost

    private void Dis_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dis_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Dis_noActionPerformed

    private void Dis_noKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Dis_noKeyReleased
        char c = (char) evt.getKeyCode();
        if (c == KeyEvent.VK_UP) {
            jCheckBox3.grabFocus();
        }
        if (c == KeyEvent.VK_DOWN) {
            jCheckBox1.grabFocus();
        }
    }//GEN-LAST:event_Dis_noKeyReleased

    private void Dis_noKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Dis_noKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_Dis_noKeyTyped

    private void jCheckBox1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCheckBox1KeyReleased
        char c = (char) evt.getKeyCode();
        if (c == KeyEvent.VK_UP) {
            Dis_no.grabFocus();
        }
        if (c == KeyEvent.VK_DOWN) {
            Update.grabFocus();
        }
    }//GEN-LAST:event_jCheckBox1KeyReleased

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCheckBox3KeyReleased
        char c = (char) evt.getKeyCode();
        if (c == KeyEvent.VK_UP) {
            jDateChooser1.grabFocus();
        }
        if (c == KeyEvent.VK_DOWN) {
            Dis_no.grabFocus();
        }
    }//GEN-LAST:event_jCheckBox3KeyReleased

    private void jCheckBox3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCheckBox3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3KeyTyped

    private void add_1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_add_1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_add_1KeyTyped

    private void add_1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_add_1KeyReleased

        char c = (char) evt.getKeyCode();
        if (c == KeyEvent.VK_UP) {
            c_name.grabFocus();
        }
        if (c == KeyEvent.VK_DOWN) {
            add_2.grabFocus();
        }
    }//GEN-LAST:event_add_1KeyReleased

    private void add_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_1ActionPerformed
        add_2.grabFocus();
    }//GEN-LAST:event_add_1ActionPerformed

    private void add_1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_add_1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_add_1FocusLost

    private void add_1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_add_1FocusGained
        add_1.selectAll();
    }//GEN-LAST:event_add_1FocusGained

    private void UpdateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UpdateKeyReleased
        char c = (char) evt.getKeyCode();
        if (c == KeyEvent.VK_RIGHT) {
            Save.grabFocus();
        }

    }//GEN-LAST:event_UpdateKeyReleased

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        //      idcustomer, name, address_1, address_2, address_3, city, tp1, tp2, nic, dob, gender, status, loyalty_discount_idloyalty_discount
        String status = "";
        if (jCheckBox1.isSelected()) {
            status = "1";
        } else if (jCheckBox2.isSelected()) {
            status = "0";
        }
        String gender = "";
        if (jCheckBox3.isSelected()) {
            gender = "Male";
        } else {
            gender = "Female";
        }
        Date d1 = jDateChooser1.getDate();
        SimpleDateFormat sf = new SimpleDateFormat("yyyy-MM-dd");
        String d = sf.format(d1);
        int k = JOptionPane.showConfirmDialog(this, "Do you want to update this data ?", "WARNING !", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (k == 0) {

            try {
                DB.MyDB.iud("Update customer set name='" + c_name.getText() + "',address_1='" + add_1.getText() + "',address_2='" + add_2.getText() + "',address_3='" + add_3.getText() + "',city='" + city_c.getText() + "',tp1='" + Tel_no.getText() + "',tp2='" + Tel_home.getText() + "',nic='" + nic.getText() + "',dob='" + d + "',gender='" + gender + "',loyalty_discount_idloyalty_discount='" + Dis_no.getText() + "',status='" + status + "' where idcustomer='" + cus_id.getText() + "'");
                JOptionPane.showMessageDialog(this, "Successfully updated");
                c_name.setText("");
                add_1.setText("");
                add_2.setText("");
                add_3.setText("");
                city_c.setText("");
                Tel_no.setText("");
                Tel_home.setText("");
                nic.setText("");
                jCheckBox3.setSelected(true);
                Dis_no.setText("");
                jCheckBox1.setSelected(true);

                GenerateID();
                cus_id.grabFocus();

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_UpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField Dis_no;
    private javax.swing.JButton Save;
    public static javax.swing.JTextField Tel_home;
    public static javax.swing.JTextField Tel_no;
    private javax.swing.JButton Update;
    public static javax.swing.JTextField add_1;
    public static javax.swing.JTextField add_2;
    public static javax.swing.JTextField add_3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    public static javax.swing.JTextField c_name;
    public static javax.swing.JTextField city_c;
    public static javax.swing.JTextField cus_id;
    public static javax.swing.JCheckBox jCheckBox1;
    public static javax.swing.JCheckBox jCheckBox2;
    public static javax.swing.JCheckBox jCheckBox3;
    public static javax.swing.JCheckBox jCheckBox4;
    public static com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel13;
    public static javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    public static javax.swing.JLabel jLabel16;
    public static javax.swing.JLabel jLabel17;
    public static javax.swing.JLabel jLabel18;
    public static javax.swing.JLabel jLabel19;
    public static javax.swing.JLabel jLabel20;
    public static javax.swing.JLabel jLabel21;
    public static javax.swing.JLabel jLabel22;
    public static javax.swing.JLabel jLabel23;
    public static javax.swing.JLabel jLabel24;
    public static javax.swing.JLabel jLabel25;
    public static javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField nic;
    // End of variables declaration//GEN-END:variables
 public static void GenerateID() {
//        idcustomer, name, address_1, address_2, address_3, city, tp1, tp2, nic, dob, gender, status, loyalty_discount_idloyalty_discount
        try {
            ResultSet rs = DB.MyDB.search("select max(idcustomer) from customer");
            if (rs.next()) {
                cus_id.setText(Integer.parseInt(rs.getString("max(idcustomer)")) + 1 + "");
            } else {
                cus_id.setText("1");
            }
        } catch (Exception e) {
            cus_id.setText("1");
        }
    }

    public static void search() {
        try {
            ResultSet rs = DB.MyDB.search("select * from customer where idcustomer= '" + cus_id.getText() + "'");
            //idcustomer, name, address_1, address_2, address_3, city, tp1, tp2, nic, dob, gender, status, loyalty_discount_idloyalty_discount"
            if (rs.next()) {
                cus_id.setText(rs.getString("idcustomer"));
                c_name.setText(rs.getString("name"));
                add_1.setText(rs.getString("address_1"));
                add_2.setText(rs.getString("address_2"));
                add_3.setText(rs.getString("address_3"));
                city_c.setText(rs.getString("city"));
                Tel_no.setText(rs.getString("tp1"));
                Tel_home.setText(rs.getString("tp2"));
                jDateChooser1.setDate(java.sql.Date.valueOf(rs.getString("dob")));
                Dis_no.setText(rs.getString("loyalty_discount_idloyalty_discount"));
                nic.setText(rs.getString("nic"));
                if (rs.getString("gender").equals("Male")) {
                    jCheckBox3.setSelected(true);
                } else {
                    jCheckBox4.setSelected(true);
                }
                if (rs.getString("status").equals("1")) {
                    jCheckBox1.setSelected(true);
                } else {
                    jCheckBox2.setSelected(true);

                }
                c_name.grabFocus();
            } else {
                c_name.setText("");
                add_1.setText("");
                add_2.setText("");
                add_3.setText("");
                city_c.setText("");
                Tel_no.setText("");
                Tel_home.setText("");
                nic.setText("");
                Dis_no.setText("");
                jCheckBox3.setSelectedIcon(null);
                jCheckBox4.setSelectedIcon(null);
                Dis_no.setText("");
                jCheckBox1.setSelected(true);
                GenerateID();
                c_name.grabFocus();

            }

        } catch (Exception e) {
        }
    }
}
