/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package EMP_06_Kapuge;

import java.awt.Image;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Owner
 */
public class Employee extends javax.swing.JFrame {

    /**
     * Creates new form Employee
     */
    public Employee() {
        initComponents();
         GenerateID();
         ImageIcon imageicon = new ImageIcon(getClass().getResource("/images/logo.png"));
        Image image = imageicon.getImage();
        setIconImage(image);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        id = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        l1 = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        empID = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        l2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        l3 = new javax.swing.JTextField();
        city = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        cn = new javax.swing.JTextField();
        nic = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        home = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        act = new javax.swing.JCheckBox();
        inact = new javax.swing.JCheckBox();
        male = new javax.swing.JCheckBox();
        female = new javax.swing.JCheckBox();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        id.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Employee Details");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Address Line 1");

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        l1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                l1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                l1FocusLost(evt);
            }
        });
        l1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l1ActionPerformed(evt);
            }
        });
        l1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                l1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                l1KeyTyped(evt);
            }
        });

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Employee Name");

        empID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        empID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                empIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                empIDFocusLost(evt);
            }
        });
        empID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empIDActionPerformed(evt);
            }
        });
        empID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                empIDKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                empIDKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Employee  ID");

        name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameFocusLost(evt);
            }
        });
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameKeyTyped(evt);
            }
        });

        l2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                l2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                l2FocusLost(evt);
            }
        });
        l2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l2ActionPerformed(evt);
            }
        });
        l2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                l2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                l2KeyTyped(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Address Line 2");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("City");

        l3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                l3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                l3FocusLost(evt);
            }
        });
        l3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l3ActionPerformed(evt);
            }
        });
        l3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                l3KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                l3KeyTyped(evt);
            }
        });

        city.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        city.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cityFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cityFocusLost(evt);
            }
        });
        city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityActionPerformed(evt);
            }
        });
        city.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cityKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cityKeyTyped(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("Address Line 3");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("Contact Number Home");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("Date Of Birth");

        cn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cnFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cnFocusLost(evt);
            }
        });
        cn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnActionPerformed(evt);
            }
        });
        cn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cnKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cnKeyTyped(evt);
            }
        });

        nic.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nic.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nicFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nicFocusLost(evt);
            }
        });
        nic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicActionPerformed(evt);
            }
        });
        nic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nicKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nicKeyTyped(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("NIC");

        home.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        home.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                homeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                homeFocusLost(evt);
            }
        });
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        home.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                homeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                homeKeyTyped(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("Contact Number");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel23.setText("Status");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel24.setText("Gender");

        buttonGroup2.add(act);
        act.setSelected(true);
        act.setText("Active");
        act.setContentAreaFilled(false);

        buttonGroup2.add(inact);
        inact.setText("Inactive");
        inact.setContentAreaFilled(false);

        buttonGroup1.add(male);
        male.setSelected(true);
        male.setText("Male");
        male.setContentAreaFilled(false);
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        male.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                maleKeyReleased(evt);
            }
        });

        buttonGroup1.add(female);
        female.setText("Female");
        female.setContentAreaFilled(false);
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout idLayout = new javax.swing.GroupLayout(id);
        id.setLayout(idLayout);
        idLayout.setHorizontalGroup(
            idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(idLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(idLayout.createSequentialGroup()
                        .addGroup(idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                            .addGroup(idLayout.createSequentialGroup()
                                .addGroup(idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(50, 50, 50))
                    .addGroup(idLayout.createSequentialGroup()
                        .addGroup(idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(l3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(empID, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, idLayout.createSequentialGroup()
                            .addComponent(update)
                            .addGap(28, 28, 28)
                            .addComponent(save)))
                    .addGroup(idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(nic, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                        .addComponent(home, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                        .addComponent(cn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                        .addComponent(city, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                    .addGroup(idLayout.createSequentialGroup()
                        .addComponent(male)
                        .addGap(18, 18, 18)
                        .addComponent(female))
                    .addGroup(idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(idLayout.createSequentialGroup()
                            .addComponent(act)
                            .addGap(18, 18, 18)
                            .addComponent(inact))))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        idLayout.setVerticalGroup(
            idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, idLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel15)
                .addGap(63, 63, 63)
                .addGroup(idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(empID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGroup(idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(idLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(male)
                            .addComponent(female)))
                    .addGroup(idLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel24)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(act)
                    .addComponent(inact))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(update)
                    .addComponent(save))
                .addGap(69, 69, 69))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed

        if (empID.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please complete the form !");
            empID.grabFocus();
        } else if (name.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please complete the form !");
            name.grabFocus();
        } else if (l1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please complete the form !");
            l1.grabFocus();
        } else if (l2.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please complete the form !");
            l2.grabFocus();
        } else if (l3.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please complete the form !");
            l3.grabFocus();
        } else if (city.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please complete the form !");
            city.grabFocus();
        } else if (cn.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please complete the form !");
            cn.grabFocus();
        } else if (home.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please complete the form !");
            home.grabFocus();
        } else if (nic.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please complete the form !");
            nic.grabFocus();
        } else {
            String status = "";
            if (act.isSelected()) {
                status = "1";
            } else if (inact.isSelected()) {
                status = "0";
            }

            String gender = "";
            if (male.isSelected()) {
                gender = "Male";

            } else if (female.isSelected()) {
                gender = "Female";
            }

            int k = JOptionPane.showConfirmDialog(this, "Do you want to save !", "WARNING", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (k == 0) {
                try {
                    Date d = jDateChooser1.getDate();
                    SimpleDateFormat sf = new SimpleDateFormat("yyyy-MM-dd");
                    String d1 = sf.format(d);

                    DB.MyDB.iud("insert into employee(idEmployee,name,address_1,address_2,address_3,city,contact_1,contact_2,nic,dob,gender,status) values('" + empID.getText() + "','" + name.getText() + "','" + l1.getText() + "','" + l2.getText() + "','" + l3.getText() + "','" + city.getText() + "','" + cn.getText() + "','" + home.getText() + "','" + nic.getText() + "','" + d1 + "','" + gender + "','" + status + "')");
                    JOptionPane.showMessageDialog(this, "Sussessfully saved !");
                    name.grabFocus();

                    empID.setText("");
                    name.setText("");
                    l1.setText("");
                    l2.setText("");
                    l3.setText("");
                    city.setText("");
                    cn.setText("");
                    home.setText("");
                    nic.setText("");
                    male.setSelectedIcon(null);
                    act.setSelectedIcon(null);

                    GenerateID();

                } catch (Exception e) {
                    e.printStackTrace();
                }

            }
        }
    }//GEN-LAST:event_saveActionPerformed

    private void l1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_l1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_l1FocusGained

    private void l1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_l1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_l1FocusLost

    private void l1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l1ActionPerformed
        l2.grabFocus();
    }//GEN-LAST:event_l1ActionPerformed

    private void l1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_l1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_l1KeyReleased

    private void l1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_l1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_l1KeyTyped

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed

        String gender = "";
        if (male.isSelected()) {
            gender = "Male";
        } else {
            gender = "Female";
        }

        String status = "";
        if (act.isSelected()) {
            status = "1";
        } else {
            status = "0";
        }

        int k = JOptionPane.showConfirmDialog(this, "Are you sure you want to update ?", "WARNNING!", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (k == 0) {
            Date d = jDateChooser1.getDate();
            SimpleDateFormat sf = new SimpleDateFormat("yyyy-MM-dd");
            String d1 = sf.format(d);

            try {
                DB.MyDB.iud("update employee set name = '" + name.getText() + "',address_1='" + l1.getText() + "',address_2='" + l2.getText() + "',address_3='" + l3.getText() + "',city='" + city.getText() + "',contact_1='" + cn.getText() + "',contact_2='" + home.getText() + "',nic='" + nic.getText() + "',dob='" + d1 + "',gender='" + gender + "',status ='" + status + "' where idEmployee='" + empID.getText() + "'");
            } catch (Exception e) {
                e.printStackTrace();
            }
            JOptionPane.showMessageDialog(this, "Successfully Updated !");
            empID.setText("");
            name.setText("");
            l1.setText("");
            l2.setText("");
            l3.setText("");
            city.setText("");
            cn.setText("");
            home.setText("");
            nic.setText("");
            male.setSelected(true);
            act.setSelected(true);
            GenerateID();
            name.grabFocus();
        }
    }//GEN-LAST:event_updateActionPerformed

    private void empIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_empIDFocusGained

    }//GEN-LAST:event_empIDFocusGained

    private void empIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_empIDFocusLost

    }//GEN-LAST:event_empIDFocusLost

    private void empIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empIDActionPerformed

        try {
            ResultSet rs = DB.MyDB.search("select * from employee where idEmployee = '" + empID.getText() + "' ");
            if (rs.next()) {

                name.setText(rs.getString("name"));
                l1.setText(rs.getString("address_1"));
                l2.setText(rs.getString("address_2"));
                l3.setText(rs.getString("address_3"));
                city.setText(rs.getString("city"));
                cn.setText(rs.getString("contact_1"));
                home.setText(rs.getString("contact_2"));
                nic.setText(rs.getString("nic"));

                if (rs.getString("gender").equals("Male")) {

                    male.setSelected(true);
                } else {

                    female.setSelected(true);
                }
                if (rs.getString("status").equals("1")) {
                    act.setSelected(true);
                } else {
                    inact.setSelected(true);
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        name.grabFocus();
    }//GEN-LAST:event_empIDActionPerformed

    private void empIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_empIDKeyReleased

    }//GEN-LAST:event_empIDKeyReleased

    private void empIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_empIDKeyTyped

    }//GEN-LAST:event_empIDKeyTyped

    private void nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFocusGained

    private void nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFocusLost

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        l1.grabFocus();
    }//GEN-LAST:event_nameActionPerformed

    private void nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_nameKeyReleased

    private void nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_nameKeyTyped

    private void l2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_l2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_l2FocusGained

    private void l2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_l2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_l2FocusLost

    private void l2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l2ActionPerformed
        l3.grabFocus();
    }//GEN-LAST:event_l2ActionPerformed

    private void l2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_l2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_l2KeyReleased

    private void l2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_l2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_l2KeyTyped

    private void l3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_l3FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_l3FocusGained

    private void l3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_l3FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_l3FocusLost

    private void l3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l3ActionPerformed
        city.grabFocus();
    }//GEN-LAST:event_l3ActionPerformed

    private void l3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_l3KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_l3KeyReleased

    private void l3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_l3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_l3KeyTyped

    private void cityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cityFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_cityFocusGained

    private void cityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cityFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_cityFocusLost

    private void cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityActionPerformed
        cn.grabFocus();
    }//GEN-LAST:event_cityActionPerformed

    private void cityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cityKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cityKeyReleased

    private void cityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cityKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_cityKeyTyped

    private void cnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cnFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_cnFocusGained

    private void cnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cnFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_cnFocusLost

    private void cnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnActionPerformed
        home.grabFocus();
    }//GEN-LAST:event_cnActionPerformed

    private void cnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnKeyReleased

    }//GEN-LAST:event_cnKeyReleased

    private void cnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnKeyTyped

        if (!(Character.isDigit(evt.getKeyChar()))) {
            evt.consume();
        }
        if (cn.getText().length() > 9) {
            evt.consume();
        }
    }//GEN-LAST:event_cnKeyTyped

    private void nicFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nicFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_nicFocusGained

    private void nicFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nicFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_nicFocusLost

    private void nicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicActionPerformed

    }//GEN-LAST:event_nicActionPerformed

    private void nicKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nicKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_nicKeyReleased

    private void nicKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nicKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_nicKeyTyped

    private void homeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_homeFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_homeFocusGained

    private void homeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_homeFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_homeFocusLost

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        nic.grabFocus();
    }//GEN-LAST:event_homeActionPerformed

    private void homeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_homeKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_homeKeyReleased

    private void homeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_homeKeyTyped

        if (!(Character.isDigit(evt.getKeyChar()))) {
            evt.consume();
        }
        if (home.getText().length() > 9) {
            evt.consume();
        }
    }//GEN-LAST:event_homeKeyTyped

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleActionPerformed

    private void maleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_maleKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_maleKeyReleased

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox act;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    public static javax.swing.JTextField city;
    public static javax.swing.JTextField cn;
    public static javax.swing.JTextField empID;
    private javax.swing.JCheckBox female;
    public static javax.swing.JTextField home;
    private javax.swing.JPanel id;
    private javax.swing.JCheckBox inact;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel13;
    public static javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    public static javax.swing.JLabel jLabel16;
    public static javax.swing.JLabel jLabel17;
    public static javax.swing.JLabel jLabel18;
    public static javax.swing.JLabel jLabel19;
    public static javax.swing.JLabel jLabel20;
    public static javax.swing.JLabel jLabel21;
    public static javax.swing.JLabel jLabel22;
    public static javax.swing.JLabel jLabel23;
    public static javax.swing.JLabel jLabel24;
    public static javax.swing.JLabel jLabel9;
    public static javax.swing.JTextField l1;
    public static javax.swing.JTextField l2;
    public static javax.swing.JTextField l3;
    private javax.swing.JCheckBox male;
    public static javax.swing.JTextField name;
    public static javax.swing.JTextField nic;
    private javax.swing.JButton save;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables

     private void GenerateID() {
//get the employee ID
        try {
            ResultSet rs = DB.MyDB.search("select max(idEmployee) from employee ");
            if (rs.next()) {
                empID.setText(Integer.parseInt(rs.getString("max(idEmployee)")) + 1 + "");
            }

        } catch (Exception e) {
            empID.setText("1");
        }
    }
}
